#!/bin/csh -f
set branch=$1
cp /home/taisung/amber/amber_${branch}/build/src/pmemd/src/pmemd.cuda_SPFP  /home/taisung/amber/amber_${branch}/installed/bin/

set AMBERHOME=/home/taisung/amber/amber_${branch}/installed
set sander = ${AMBERHOME}/bin/pmemd.cuda_SPFP

cat > mdin <<EOF
 short md, nve ensemble
 &cntrl
   ntx=5, irest=1,
   ntc=2, ntf=2, tol=0.0000001,
   nstlim=100000000, ntt=0,
   ntpr=1000, ntwr=10000,
   dt=0.001, ig=71277,
 /
 &ewald
   nfft1=60, nfft2=60, nfft3=60, netfrc=0,
 /
EOF

set output = mdout.$branch
set rest=restrt.$branch
set mdcrd=mdcrd.$branch
set inf=mdinfo.$branch

$sander -O -o $output -c inpcrd -r $rest -x $mdcrd -inf $inf
