#!/bin/csh -f
set branch=$1
cp /home/taisung/amber/amber_${branch}/build/src/pmemd/src/pmemd.cuda_SPFP  /home/taisung/amber/amber_${branch}/installed/bin/

set AMBERHOME=/home/taisung/amber/amber_${branch}/installed
set sander = ${AMBERHOME}/bin/pmemd.cuda_SPFP

cat > mdin <<EOF
 short md, nve ensemble, trunc oct
 &cntrl
   ntx=1, irest=0,
   ntc=2, ntf=2, tol=0.0000001,
   nstlim=20, ntt=0,
   tempi=300.0, temp0=300.0,
   ntb=1,ntp=0,
   ntpr=1, ntwr=10000, ntwx=5,
   dt=0.001, ig=71277, ioutfm=0,
 /
 &ewald
  nfft1=64,nfft2=64,nfft3=64, netfrc=0,
 /
EOF

set output = mdout.$branch
set rest=restrt.$branch
set mdcrd=mdcrd.$branch
set inf=mdinfo.$branch

$sander -O -o $output -c inpcrd -r $rest -x $mdcrd -inf $inf
